<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c2512c8a-beee-4cd6-a72b-88d2798c55b8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PatchlabNgrokSync\**" />
  </ItemGroup>

</Project>
