name: Deploy Patchlab WhatsApp Bot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Stop PatchlabWhatsAppBot service
        run: C:\nssm\win64\nssm.exe stop PatchlabWhatsAppBot

      - name: Clean PatchlabWhatsAppBot publish folder
        run: |
          if (Test-Path "C:\PatchlabWhatsAppBot\publish") {
            Get-ChildItem "C:\PatchlabWhatsAppBot\publish" -Exclude config.json |
              Remove-Item -Recurse -Force
          }
        shell: powershell

      - name: Publish PatchlabWhatsAppBot
        run: dotnet publish -c Release -o C:\PatchlabWhatsAppBot\publish

      - name: Start PatchlabWhatsAppBot service
        run: C:\nssm\win64\nssm.exe start PatchlabWhatsAppBot

      - name: Stop PatchlabNgrokSync service
        run: C:\nssm\win64\nssm.exe stop PatchlabNgrokSync

      - name: Publish PatchlabNgrokSync
        run: dotnet publish PatchlabNgrokSync\PatchlabNgrokSync.csproj -c Release -o C:\PatchlabNgrokSync\publish

      - name: Start PatchlabNgrokSync service
        run: C:\nssm\win64\nssm.exe start PatchlabNgrokSync